name: cascavel_em_numeros
description: "Inteligência Econômica - Cascavel em Números MVP"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fl_chart: ^0.64.0
  intl: ^0.19.0
  flutter_riverpod: ^2.4.9
  web: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/mock_data.json
    - assets/bairros_lista.json
